#-------------------------------
# General Site Settings

title: 欢迎来到奥术之旅
logo:
author: GonerAge project
description: this is meta description
email: lplcai@ucdavis.edu
phone: +880 2544 658 256
address: 125/A, CA Commercial Area, California, USA
copyright: Copyright &copy; 2020 Designed by [Caizii](https://space.bilibili.com/57935076) 由 [Getjekyllthemes](https://getjekyllthemes.com) 开发

menu:
- {name: 规则, link: '/about'}
- {name: 社区博客, link: '/blog'}
# - {name: 图片档案, link: '/portfolio'}
# - {name: 商店, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: 奥术之旅 <br> 沉浸式 <br> 休闲旅途

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Arcane Travel(奥术之旅)是弃用作品 奥数年代(Arcane Age) 的重制版，与其说是重制版不如说他是一个新的分支的开启，在经历过无数模组服的修改和尝试，我们打算给大家带来更加稳定和更注重社交冒险的 Arcane Travel。在这里，你将会来到一片神秘且有趣的新大陆，探索这里的一切，又或者更随着以前人们留下来的信息去探索这庞大大陆背后的故事。建立自己精致的家园，酿造出最好的药水，打造出传奇武器，这些尽在这次旅途中...
blurb-btn-link: '/about'
blurb-btn-name: 请遵守秘术规则


# About Page

# Work Process Section
work-process:
  - title : "不尊重/攻击性语言和仇恨言论"
    icon : "assets/images/icons/caltion.png"
    content : "包括种族歧视,包括但不不亚于转型别歧视等"

  - title : "故意避开聊天过滤器"
    icon : "assets/images/icons/caltion.png"
    content : "使用任何手段欺骗或者绕过聊天屏蔽器,包括使用空格，特殊符号方言等"

  - title : "任何形式的垃圾信息"
    icon : "assets/images/icons/caltion.png"
    content : "包括任何广告，无意义信息，暗语和数量众多令人困惑的信息"

  - title : "骚扰和欺负他人"
    icon : "assets/images/icons/caltion.png"
    content : "对他人进行任何语言骚扰包括频繁@他人或者对其他人进行语言暴力"

  - title : "暴露他人隐私"
    icon : "assets/images/icons/caltion.png"
    content : "暴露他人地址或者IP或按着任何有关对方不想让你提及的事情"

  - title : "宣传其他服务器"
    icon : "assets/images/icons/caltion.png"
    content : "包括但不限于推广他人服务器，发送服务器IP官网等等"
bad-behaviros:
  - title : "故意破坏他人家园"
    icon : "assets/images/icons/caltion.png"
    content : "故意破坏其他用户的家园或者领地。"
  - title : "欺诈交易"
    icon : "assets/images/icons/caltion.png"
    content : "通过交易等方式欺骗其他用户。"
  - title : "不合适的建筑或者符号"
    icon : "assets/images/icons/caltion.png"
    content : "建造令人不适的建筑或者图标包括但不限于污秽等下流符号建筑等"
  - title : "恶意PVP"
    icon : "assets/images/icons/caltion.png"
    content : "故意试图在 PVP 区域之外击杀玩家。"
third-modification:
  - title : "作弊客户端"
    icon : "assets/images/icons/caltion.png"
    content : "包括任何类型的注入和第三方功能客户端"
  - title : "非美化性客户端"
    icon : "assets/images/icons/caltion.png"
    content : "包括但不限于Forge客户端,自动助跑，自动跳跃，快速切换等内置功能"
  - title : "X-ray等资源包修改和资源"
    icon : "assets/images/icons/caltion.png"
    content : "包括但不限于x-ray材质包，x-ray客户端修改或者透明材质包等"
  - title : "连点器"
    icon : "assets/images/icons/caltion.png"
    content : "包括但不限于按键类型连点器或者挂机连点器等"
use-bug:
  - title : "Minecraft原版游戏漏洞"
    icon : "assets/images/icons/caltion.png"
    content : "包括但不限于复制物品，卡附魔，区块等。"
  - title : "服务器内部漏洞"
    icon : "assets/images/icons/caltion.png"
    content : "包括但不限于通过菜单刷物品，自定义系统的漏洞等"
# My Team Section
team:
  - title : "Caizii"
    image : "assets/images/team/member-1.png"
    designation : "项目管理"

  - title : "Kelt.J"
    image : "assets/images/team/member-2.png"
    designation : "画师"

  - title : "John Doe"
    image : "assets/images/team/member-3.png"
    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: 元素开发阶段
skills:
- {name: 生存冒险, color: '#fdb157', value: '40%'}
- {name: 物品内容, color: '#9473e6', value: '10%'}
- {name: 地牢挑战, color: '#bdecf6', value: '20%'}
- {name: 家具美化, color: '#ffbcaa', value: '40%'}

#-------------------------------
# Exprerience Section

experience-title: 元素支持
experience:
- {name: SpigotMC, icon: 'icon-1.png', date: '2012 - 2021', organization: 'SpigotMC Pty. Ltd.'}
- {name: PaperMC, icon: 'icon-2.png', date: '2015 - 2021', organization: 'The PaperMC Team'}
- {name: GonerAge, icon: 'icon-3.png', date: '2018 - 2021', organization: 'GonerAgeTeam'}


#-------------------------------
# Education Section

education-title: 里程碑
education:
- {name: 拥有清晰的目标, date: '2021', organization: '带给玩家最好的视觉和游戏体验'}
- {name: 过去的大风大浪, date: '2019', organization: '载体服务器的创建与运行'}
- {name: 冒险世界的初衷, date: '2018', organization: 'SecondTech等服务器运行'}



#-------------------------------
# Services Section

services-title: 元素特色
services:
- {
    name: 绝多的界面,
    icon: ti-palette,
    description: '就是很多',
    active:  # Add true to select section
  }
- {
    name: 技能奥术,
    icon: ti-vector,
    description: '我想想，现在有80种奥术技能?',
    active: true # Add true to select section
  }
- {
    name: 没想好,
    icon: ti-panel,
    description: '这个我也没想好该写啥',
    active: # Add true to select section
  }




#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  # - image : "assets/images/portfolio/item-1.png"
  #   url: "#"
  #
  # - image : "assets/images/portfolio/item-2.png"
  #   url: "#"
  #
  # - image : "assets/images/portfolio/item-3.png"
  #   url: "#"
  #
  # - image : "assets/images/portfolio/item-4.png"
  #   url: "#"
  #
  # - image : "assets/images/portfolio/item-5.png"
  #   url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"

  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Caizii"
    image: "assets/images/testimonial/client-1.png"
    designation : "项目创始人"
    content: "什么情况？"
  - name: "Kelt.J"
    image: "assets/images/testimonial/client-3.png"
    designation: "画师,模型制作"
    content: "啊?<strong>不会吧</strong>"
  - name: "Ruby Wu"
    image: "assets/images/testimonial/client-2.png"
    designation: "地形策划"
    content: "行行行,你说的都对"

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com
